= App config
:toc:

link:/developer_documentation/start.adoc[Back to documentation home]

== App configuration

The application environment is set in the `RACK_ENV` environment variable.

Environments can be:

* development (default)
* production
* test

Environment variable loading uses the dotenv gem (https://github.com/bkeepers/dotenv).

Development environment variables are set in the `.env` file in the root dir.

Per-machine overrides can be specified in a `.env.local` file (which is not checked in to version control).

=== Client settings

Client settings are defined in the `.env.local` file on the client's server.

Rules for environment variables are defined in `config/env_var_rules`. Whenever a new client setting is required, this file must be updated with the variable and its description.

Environment variables are classified in one of the folowing ways:

NO_OVERRIDE :: These are set in .env file and are fixed - never to be changed. e.g. `APP_CAPTION`.
CAN_OVERRIDE :: These are set in `.env`, but can be changed in `.env.local`. e.g. `DATABASE_URL`.
MUST_OVERRIDE :: These are not set in `.env` - only in `.env.local` and they are required. e.g. `SYSTEM_MAIL_SENDER`.
OPTIONAL :: These are optinal settings (typically for developers only) that do not have to be present. e.g. `LOGSQLTOFILE`.


Use `bundle exec rake developers:setup` to get `.env.local` to add any required environment variables that are missing.

=== AppConst

This file (`config/app_const.rb`) stores "global" constants for use throuhgout the application.

Reference a constant in code like this:
[source,ruby]
----
AppConst::CLIENT_CODE
----

.config/app_const.rb
[source,ruby]
----
class AppConst
  # Client-specific code
  CLIENT_CODE = ENV.fetch('CLIENT_CODE')
  IMPLEMENTATION_OWNER = ENV.fetch('IMPLEMENTATION_OWNER')   <1>

  # Constants for roles:
  ROLE_IMPLEMENTATION_OWNER = 'IMPLEMENTATION_OWNER'         <2>
  ROLE_CUSTOMER = 'CUSTOMER'

  # Que
  QUEUE_NAME = ENV.fetch('QUEUE_NAME', 'default')            <3>
end
----
<1> Set a constant from a required environment variable. If not set, the application will raise an exception and not start.
<2> A string constant value. (Not configurable via environment variable)
<3> This constant is supplied by the environment variable but has a default value if there is no ENV var.
