---
:caption: Production Regions
:sql: "SELECT \"production_regions\".\"id\", \"production_regions\".\"production_region_code\",
  \"production_regions\".\"description\", \"production_regions\".\"active\", \"production_regions\".\"created_at\",
  \"production_regions\".\"updated_at\"\r\nFROM \"production_regions\""
:limit: 
:offset: 
:external_settings: {}
:columns:
  id:
    :name: id
    :sequence_no: 1
    :caption: Id
    :namespaced_name: production_regions.id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  production_region_code:
    :name: production_region_code
    :sequence_no: 2
    :caption: Production region code
    :namespaced_name: production_regions.production_region_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  description:
    :name: description
    :sequence_no: 3
    :caption: Description
    :namespaced_name: production_regions.description
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  active:
    :name: active
    :sequence_no: 4
    :caption: Active
    :namespaced_name: production_regions.active
    :data_type: :boolean
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  created_at:
    :name: created_at
    :sequence_no: 5
    :caption: Created at
    :namespaced_name: production_regions.created_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  updated_at:
    :name: updated_at
    :sequence_no: 6
    :caption: Updated at
    :namespaced_name: production_regions.updated_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
:query_parameter_definitions:
- :column: production_regions.production_region_code
  :caption: Production region code
  :data_type: :string
  :control_type: :text
  :default_value: 
  :ordered_list: false
  :ui_priority: 1
  :list_def: 
